### ISSUE TITLE
Include carousel in framework?

### ISSUE THREAD

**Issue by skoolbus39** [digitalcampusframework/dcf#11]
[Do we include a carousel in the framework?](http://shouldiuseacarousel.com/) If so, [it _must_ be accessible](https://www.w3.org/WAI/tutorials/carousels/). If so, third party or write our own?

**Comment by skoolbus39** [comment]
Some potential third-party carousels to investigate:
- [jonathantneal/carousel](https://github.com/jonathantneal/carousel)
- [arafeek/carousel](https://github.com/arafeek/carousel)
- [ginader/Accessible-Carousel](https://github.com/ginader/Accessible-Carousel)
- [khawley/carousel](https://github.com/khawley/carousel)
- [rtrvrtg/owlcarousel2-a11ylayer](https://github.com/rtrvrtg/owlcarousel2-a11ylayer), an accessibility layer for [Owl Carousel 2](https://owlcarousel2.github.io/OwlCarousel2/)
- [courgette/carotte](https://github.com/courgette/carotte)
- [estelle/carousel-carousel](https://github.com/estelle/carousel-carousel)
- [giulianok/accessible-carousel](https://github.com/giulianok/accessible-carousel)
- [aozora/a11y-carousel](https://github.com/aozora/a11y-carousel)
- [pdincubus/Accessible-Horse-Tornado](https://github.com/pdincubus/Accessible-Horse-Tornado)
- [fraddski/a11ycarousel](https://github.com/fraddski/a11ycarousel)
- [chapeljuice/best-carousel-ever](https://github.com/chapeljuice/best-carousel-ever)
- [Flickity](https://flickity.metafizzy.co/)

**Comment by tlemburg** [comment]
Carousel should probably be included, but absolutely not promoted as THE hero/frontpage/landing page solution.

That said, I would make inclusion of the carousel one of the last tasks i.e. not high priority.

**Comment by skoolbus39** [comment]
A slideshow (carousel) was added with #349, #350 and #351
