### ISSUE TITLE
.dcf-form breaks <input type="range">

### ISSUE THREAD

**Issue by ncolgrove** [digitalcampusframework/dcf#360]
![5 0 Classes | Web Developer Network | Nebraska 2020-07-30 14-27-10](https://user-images.githubusercontent.com/5377727/88966156-7daf4f80-d271-11ea-9152-1d65f258d8f5.png)

The "appearance: none" declaration in [_components.forms.scss](https://github.com/digitalcampusframework/dcf/blob/master/assets/src/scss/components/_components.forms.scss) seems to break default style and functionality for range inputs. At minimum, I would recommend adding :not([type="range"]) to the initial css rule in the file. Other css rules may be needed to further support.

**Comment by skoolbus39** [comment]
Thanks for filing this issue, @ncolgrove
